// This file is generated by rust-protobuf 2.27.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `tensorflow/tsl/protobuf/coordination_config.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_27_1;

#[derive(PartialEq,Clone,Default)]
pub struct CoordinatedJob {
    // message fields
    pub name: ::std::string::String,
    pub num_tasks: i32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a CoordinatedJob {
    fn default() -> &'a CoordinatedJob {
        <CoordinatedJob as ::protobuf::Message>::default_instance()
    }
}

impl CoordinatedJob {
    pub fn new() -> CoordinatedJob {
        ::std::default::Default::default()
    }

    // string name = 1;


    pub fn get_name(&self) -> &str {
        &self.name
    }
    pub fn clear_name(&mut self) {
        self.name.clear();
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        &mut self.name
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.name, ::std::string::String::new())
    }

    // int32 num_tasks = 2;


    pub fn get_num_tasks(&self) -> i32 {
        self.num_tasks
    }
    pub fn clear_num_tasks(&mut self) {
        self.num_tasks = 0;
    }

    // Param is passed by value, moved
    pub fn set_num_tasks(&mut self, v: i32) {
        self.num_tasks = v;
    }
}

impl ::protobuf::Message for CoordinatedJob {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.name)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.num_tasks = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        if self.num_tasks != 0 {
            my_size += ::protobuf::rt::value_size(2, self.num_tasks, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        if self.num_tasks != 0 {
            os.write_int32(2, self.num_tasks)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> CoordinatedJob {
        CoordinatedJob::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "name",
                |m: &CoordinatedJob| { &m.name },
                |m: &mut CoordinatedJob| { &mut m.name },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "num_tasks",
                |m: &CoordinatedJob| { &m.num_tasks },
                |m: &mut CoordinatedJob| { &mut m.num_tasks },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<CoordinatedJob>(
                "CoordinatedJob",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static CoordinatedJob {
        static instance: ::protobuf::rt::LazyV2<CoordinatedJob> = ::protobuf::rt::LazyV2::INIT;
        instance.get(CoordinatedJob::new)
    }
}

impl ::protobuf::Clear for CoordinatedJob {
    fn clear(&mut self) {
        self.name.clear();
        self.num_tasks = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for CoordinatedJob {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CoordinatedJob {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct CoordinationServiceConfig {
    // message fields
    pub service_type: ::std::string::String,
    pub service_leader: ::std::string::String,
    pub enable_health_check: bool,
    pub cluster_register_timeout_in_ms: i64,
    pub heartbeat_timeout_in_ms: i64,
    pub coordinated_job_list: ::protobuf::RepeatedField<CoordinatedJob>,
    pub shutdown_barrier_timeout_in_ms: i64,
    pub agent_destruction_without_shutdown: bool,
    pub recoverable_jobs: ::protobuf::RepeatedField<::std::string::String>,
    pub allow_new_incarnation_to_reconnect: bool,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a CoordinationServiceConfig {
    fn default() -> &'a CoordinationServiceConfig {
        <CoordinationServiceConfig as ::protobuf::Message>::default_instance()
    }
}

impl CoordinationServiceConfig {
    pub fn new() -> CoordinationServiceConfig {
        ::std::default::Default::default()
    }

    // string service_type = 1;


    pub fn get_service_type(&self) -> &str {
        &self.service_type
    }
    pub fn clear_service_type(&mut self) {
        self.service_type.clear();
    }

    // Param is passed by value, moved
    pub fn set_service_type(&mut self, v: ::std::string::String) {
        self.service_type = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_service_type(&mut self) -> &mut ::std::string::String {
        &mut self.service_type
    }

    // Take field
    pub fn take_service_type(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.service_type, ::std::string::String::new())
    }

    // string service_leader = 2;


    pub fn get_service_leader(&self) -> &str {
        &self.service_leader
    }
    pub fn clear_service_leader(&mut self) {
        self.service_leader.clear();
    }

    // Param is passed by value, moved
    pub fn set_service_leader(&mut self, v: ::std::string::String) {
        self.service_leader = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_service_leader(&mut self) -> &mut ::std::string::String {
        &mut self.service_leader
    }

    // Take field
    pub fn take_service_leader(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.service_leader, ::std::string::String::new())
    }

    // bool enable_health_check = 3;


    pub fn get_enable_health_check(&self) -> bool {
        self.enable_health_check
    }
    pub fn clear_enable_health_check(&mut self) {
        self.enable_health_check = false;
    }

    // Param is passed by value, moved
    pub fn set_enable_health_check(&mut self, v: bool) {
        self.enable_health_check = v;
    }

    // int64 cluster_register_timeout_in_ms = 4;


    pub fn get_cluster_register_timeout_in_ms(&self) -> i64 {
        self.cluster_register_timeout_in_ms
    }
    pub fn clear_cluster_register_timeout_in_ms(&mut self) {
        self.cluster_register_timeout_in_ms = 0;
    }

    // Param is passed by value, moved
    pub fn set_cluster_register_timeout_in_ms(&mut self, v: i64) {
        self.cluster_register_timeout_in_ms = v;
    }

    // int64 heartbeat_timeout_in_ms = 5;


    pub fn get_heartbeat_timeout_in_ms(&self) -> i64 {
        self.heartbeat_timeout_in_ms
    }
    pub fn clear_heartbeat_timeout_in_ms(&mut self) {
        self.heartbeat_timeout_in_ms = 0;
    }

    // Param is passed by value, moved
    pub fn set_heartbeat_timeout_in_ms(&mut self, v: i64) {
        self.heartbeat_timeout_in_ms = v;
    }

    // repeated .tensorflow.CoordinatedJob coordinated_job_list = 10;


    pub fn get_coordinated_job_list(&self) -> &[CoordinatedJob] {
        &self.coordinated_job_list
    }
    pub fn clear_coordinated_job_list(&mut self) {
        self.coordinated_job_list.clear();
    }

    // Param is passed by value, moved
    pub fn set_coordinated_job_list(&mut self, v: ::protobuf::RepeatedField<CoordinatedJob>) {
        self.coordinated_job_list = v;
    }

    // Mutable pointer to the field.
    pub fn mut_coordinated_job_list(&mut self) -> &mut ::protobuf::RepeatedField<CoordinatedJob> {
        &mut self.coordinated_job_list
    }

    // Take field
    pub fn take_coordinated_job_list(&mut self) -> ::protobuf::RepeatedField<CoordinatedJob> {
        ::std::mem::replace(&mut self.coordinated_job_list, ::protobuf::RepeatedField::new())
    }

    // int64 shutdown_barrier_timeout_in_ms = 7;


    pub fn get_shutdown_barrier_timeout_in_ms(&self) -> i64 {
        self.shutdown_barrier_timeout_in_ms
    }
    pub fn clear_shutdown_barrier_timeout_in_ms(&mut self) {
        self.shutdown_barrier_timeout_in_ms = 0;
    }

    // Param is passed by value, moved
    pub fn set_shutdown_barrier_timeout_in_ms(&mut self, v: i64) {
        self.shutdown_barrier_timeout_in_ms = v;
    }

    // bool agent_destruction_without_shutdown = 8;


    pub fn get_agent_destruction_without_shutdown(&self) -> bool {
        self.agent_destruction_without_shutdown
    }
    pub fn clear_agent_destruction_without_shutdown(&mut self) {
        self.agent_destruction_without_shutdown = false;
    }

    // Param is passed by value, moved
    pub fn set_agent_destruction_without_shutdown(&mut self, v: bool) {
        self.agent_destruction_without_shutdown = v;
    }

    // repeated string recoverable_jobs = 9;


    pub fn get_recoverable_jobs(&self) -> &[::std::string::String] {
        &self.recoverable_jobs
    }
    pub fn clear_recoverable_jobs(&mut self) {
        self.recoverable_jobs.clear();
    }

    // Param is passed by value, moved
    pub fn set_recoverable_jobs(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.recoverable_jobs = v;
    }

    // Mutable pointer to the field.
    pub fn mut_recoverable_jobs(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.recoverable_jobs
    }

    // Take field
    pub fn take_recoverable_jobs(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.recoverable_jobs, ::protobuf::RepeatedField::new())
    }

    // bool allow_new_incarnation_to_reconnect = 11;


    pub fn get_allow_new_incarnation_to_reconnect(&self) -> bool {
        self.allow_new_incarnation_to_reconnect
    }
    pub fn clear_allow_new_incarnation_to_reconnect(&mut self) {
        self.allow_new_incarnation_to_reconnect = false;
    }

    // Param is passed by value, moved
    pub fn set_allow_new_incarnation_to_reconnect(&mut self, v: bool) {
        self.allow_new_incarnation_to_reconnect = v;
    }
}

impl ::protobuf::Message for CoordinationServiceConfig {
    fn is_initialized(&self) -> bool {
        for v in &self.coordinated_job_list {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.service_type)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.service_leader)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.enable_health_check = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.cluster_register_timeout_in_ms = tmp;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.heartbeat_timeout_in_ms = tmp;
                },
                10 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.coordinated_job_list)?;
                },
                7 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.shutdown_barrier_timeout_in_ms = tmp;
                },
                8 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.agent_destruction_without_shutdown = tmp;
                },
                9 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.recoverable_jobs)?;
                },
                11 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.allow_new_incarnation_to_reconnect = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.service_type.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.service_type);
        }
        if !self.service_leader.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.service_leader);
        }
        if self.enable_health_check != false {
            my_size += 2;
        }
        if self.cluster_register_timeout_in_ms != 0 {
            my_size += ::protobuf::rt::value_size(4, self.cluster_register_timeout_in_ms, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.heartbeat_timeout_in_ms != 0 {
            my_size += ::protobuf::rt::value_size(5, self.heartbeat_timeout_in_ms, ::protobuf::wire_format::WireTypeVarint);
        }
        for value in &self.coordinated_job_list {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        if self.shutdown_barrier_timeout_in_ms != 0 {
            my_size += ::protobuf::rt::value_size(7, self.shutdown_barrier_timeout_in_ms, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.agent_destruction_without_shutdown != false {
            my_size += 2;
        }
        for value in &self.recoverable_jobs {
            my_size += ::protobuf::rt::string_size(9, &value);
        };
        if self.allow_new_incarnation_to_reconnect != false {
            my_size += 2;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.service_type.is_empty() {
            os.write_string(1, &self.service_type)?;
        }
        if !self.service_leader.is_empty() {
            os.write_string(2, &self.service_leader)?;
        }
        if self.enable_health_check != false {
            os.write_bool(3, self.enable_health_check)?;
        }
        if self.cluster_register_timeout_in_ms != 0 {
            os.write_int64(4, self.cluster_register_timeout_in_ms)?;
        }
        if self.heartbeat_timeout_in_ms != 0 {
            os.write_int64(5, self.heartbeat_timeout_in_ms)?;
        }
        for v in &self.coordinated_job_list {
            os.write_tag(10, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        if self.shutdown_barrier_timeout_in_ms != 0 {
            os.write_int64(7, self.shutdown_barrier_timeout_in_ms)?;
        }
        if self.agent_destruction_without_shutdown != false {
            os.write_bool(8, self.agent_destruction_without_shutdown)?;
        }
        for v in &self.recoverable_jobs {
            os.write_string(9, &v)?;
        };
        if self.allow_new_incarnation_to_reconnect != false {
            os.write_bool(11, self.allow_new_incarnation_to_reconnect)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> CoordinationServiceConfig {
        CoordinationServiceConfig::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "service_type",
                |m: &CoordinationServiceConfig| { &m.service_type },
                |m: &mut CoordinationServiceConfig| { &mut m.service_type },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "service_leader",
                |m: &CoordinationServiceConfig| { &m.service_leader },
                |m: &mut CoordinationServiceConfig| { &mut m.service_leader },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                "enable_health_check",
                |m: &CoordinationServiceConfig| { &m.enable_health_check },
                |m: &mut CoordinationServiceConfig| { &mut m.enable_health_check },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                "cluster_register_timeout_in_ms",
                |m: &CoordinationServiceConfig| { &m.cluster_register_timeout_in_ms },
                |m: &mut CoordinationServiceConfig| { &mut m.cluster_register_timeout_in_ms },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                "heartbeat_timeout_in_ms",
                |m: &CoordinationServiceConfig| { &m.heartbeat_timeout_in_ms },
                |m: &mut CoordinationServiceConfig| { &mut m.heartbeat_timeout_in_ms },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<CoordinatedJob>>(
                "coordinated_job_list",
                |m: &CoordinationServiceConfig| { &m.coordinated_job_list },
                |m: &mut CoordinationServiceConfig| { &mut m.coordinated_job_list },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                "shutdown_barrier_timeout_in_ms",
                |m: &CoordinationServiceConfig| { &m.shutdown_barrier_timeout_in_ms },
                |m: &mut CoordinationServiceConfig| { &mut m.shutdown_barrier_timeout_in_ms },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                "agent_destruction_without_shutdown",
                |m: &CoordinationServiceConfig| { &m.agent_destruction_without_shutdown },
                |m: &mut CoordinationServiceConfig| { &mut m.agent_destruction_without_shutdown },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "recoverable_jobs",
                |m: &CoordinationServiceConfig| { &m.recoverable_jobs },
                |m: &mut CoordinationServiceConfig| { &mut m.recoverable_jobs },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                "allow_new_incarnation_to_reconnect",
                |m: &CoordinationServiceConfig| { &m.allow_new_incarnation_to_reconnect },
                |m: &mut CoordinationServiceConfig| { &mut m.allow_new_incarnation_to_reconnect },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<CoordinationServiceConfig>(
                "CoordinationServiceConfig",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static CoordinationServiceConfig {
        static instance: ::protobuf::rt::LazyV2<CoordinationServiceConfig> = ::protobuf::rt::LazyV2::INIT;
        instance.get(CoordinationServiceConfig::new)
    }
}

impl ::protobuf::Clear for CoordinationServiceConfig {
    fn clear(&mut self) {
        self.service_type.clear();
        self.service_leader.clear();
        self.enable_health_check = false;
        self.cluster_register_timeout_in_ms = 0;
        self.heartbeat_timeout_in_ms = 0;
        self.coordinated_job_list.clear();
        self.shutdown_barrier_timeout_in_ms = 0;
        self.agent_destruction_without_shutdown = false;
        self.recoverable_jobs.clear();
        self.allow_new_incarnation_to_reconnect = false;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for CoordinationServiceConfig {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CoordinationServiceConfig {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n1tensorflow/tsl/protobuf/coordination_config.proto\x12\ntensorflow\"A\
    \n\x0eCoordinatedJob\x12\x12\n\x04name\x18\x01\x20\x01(\tR\x04name\x12\
    \x1b\n\tnum_tasks\x18\x02\x20\x01(\x05R\x08numTasks\"\xec\x04\n\x19Coord\
    inationServiceConfig\x12!\n\x0cservice_type\x18\x01\x20\x01(\tR\x0bservi\
    ceType\x12%\n\x0eservice_leader\x18\x02\x20\x01(\tR\rserviceLeader\x12.\
    \n\x13enable_health_check\x18\x03\x20\x01(\x08R\x11enableHealthCheck\x12\
    B\n\x1ecluster_register_timeout_in_ms\x18\x04\x20\x01(\x03R\x1aclusterRe\
    gisterTimeoutInMs\x125\n\x17heartbeat_timeout_in_ms\x18\x05\x20\x01(\x03\
    R\x14heartbeatTimeoutInMs\x12L\n\x14coordinated_job_list\x18\n\x20\x03(\
    \x0b2\x1a.tensorflow.CoordinatedJobR\x12coordinatedJobList\x12B\n\x1eshu\
    tdown_barrier_timeout_in_ms\x18\x07\x20\x01(\x03R\x1ashutdownBarrierTime\
    outInMs\x12K\n\"agent_destruction_without_shutdown\x18\x08\x20\x01(\x08R\
    \x1fagentDestructionWithoutShutdown\x12)\n\x10recoverable_jobs\x18\t\x20\
    \x03(\tR\x0frecoverableJobs\x12J\n\"allow_new_incarnation_to_reconnect\
    \x18\x0b\x20\x01(\x08R\x1eallowNewIncarnationToReconnectJ\x04\x08\x06\
    \x10\x07BWZUgithub.com/tensorflow/tensorflow/tensorflow/go/core/protobuf\
    /for_core_protos_go_protob\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
